# Generated by Django 4.2 on 2023-06-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='consultarDisciplina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='incluirDisciplina',
            field=models.BooleanField(default=False),
        ),
    ]
