# Generated by Django 4.2 on 2023-06-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='registrarAluno',
            field=models.BooleanField(default=False),
        ),
    ]
