# Generated by Django 4.2 on 2023-06-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_aluno_registraraluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='alterarAluno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='consultarAluno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='excluirAluno',
            field=models.BooleanField(default=False),
        ),
    ]
