# Generated by Django 4.2 on 2023-06-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='consultarCurso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='incluirCurso',
            field=models.BooleanField(default=False),
        ),
    ]
