# Generated by Django 4.2 on 2023-06-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='consultarTurma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professor',
            name='lancarNotaAluno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professor',
            name='realizarFrequencia',
            field=models.BooleanField(default=False),
        ),
    ]
