# Generated by Django 4.2 on 2023-06-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='listarAlunos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turma',
            name='listarTurma',
            field=models.BooleanField(default=False),
        ),
    ]
